/*DROP TABLE IF EXISTS User;

CREATE TABLE User (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    surname VARCHAR(250) NOT NULL,
    phone_number VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    address VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
);*/